--- 
- hosts: all
  become: true
  tasks:
 
  - name: update repository index
    apt:
     update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: present
  
  - name: add PHP support for apache
    apt:
      name: php
      state: present 
